name: OTT Collector Test

on:
  workflow_dispatch:

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.x"

      - name: Run collector
        run: |
          python collector.py

      - name: Show result
        run: |
          echo "=============================="
          echo "OTT COLLECTOR RESULT"
          echo "=============================="
          cat test_result.json

      - name: Save result
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          git add test_result.json

          if git diff --cached --quiet; then
            echo "No changes to commit"
            exit 0
          fi

          git commit -m "Test OTT ranking collector"
          git push
